.PHONY: clean

pointerqueue:
	@chmod 755 .
	@python pointerqueue.py

loctree:
	@chmod 755 .
	@python loctree.py

lcrstree:
	@chmod 755 .
	@python lcrstree.py

time:
	@chmod 755 .
	@python timing.py

mergelists:
	@chmod 755 .
	@python mergelists.py

listconcat:
	@chmod 755 .
	@python listconcat.py

levelorder:
	@chmod 755 .
	@python levelorder.py
	
preorder:
	@chmod 755 .
	@python preorder.py

postorder:
	@chmod 755 .
	@python postorder.py

clean:
	@\rm -f *.pyc
