# Description: 	This is a makefile to compile all the files for Programming Assignment 1

.PHONY: clean

timing:
		@chmod 755 .
		@python timing.py

arraylist:
		@chmod 755 .
		@python arraylist.py

pointerlist:
		@chmod 755 .
		@python pointerlist.py

arraystack:
		@chmod 755 .
		@python arraystack.py

pointerstack:
		@chmod 755 .
		@python pointerstack.py

clean:
		@\rm -f *.pyc
