.PHONY: clean

PI=python

openhash:
	@chmod 755 .
	$(PI) openhash.py

closedhash:
	@chmod 755 .
	$(PI) closedhash.py

pot:
	@chmod 755 .
	$(PI) pot.py

bst:
	@chmod 755 .
	$(PI) bst.py

trie:
	@chmod 755 .
	$(PI) trie.py < Alice-in-Wonderland.txt

dfs:
	@chmod 755 .
	$(PI) dfs.py

clean:
	@\rm -f *.pyc
